###服务启动端口号
server:
  port: 8001
###服务名称(服务注册到eureka名称)  
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    prefix: classpath:/templates/
    content-type: text/html
    encoding: UTF-8
    suffix: .html
  application:
    name: app-itmayiedu-order
###服务注册到eureka地址
feign:
  hystrix:
    enabled: true
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka,http://localhost:8200/eureka,http://localhost:8300/eureka
    register-with-eureka: true
    fetch-registry: true
